FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y telnet && \
    rm -rf /var/lib/apt/lists/*

#устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["pytest", "-s"]